### ISSUE TITLE
Weird behavior if interval parameter is string 

### ISSUE THREAD

**Issue by micgeronimo** [jkbrzt/rrule#118]
Try this 
var rule = new RRule({
    freq: RRule.DAILY,
    interval: '1',
    dtstart: new Date(2016, 1, 1, 10, 30),
    until: new Date(2016, 1, 12)
});
It should have generated 11 repeats from January 1 to January 12
But this is what we receive if call rule.all()
[Mon Feb 01 2016 10:30:00 GMT+0200 (EET), Thu Feb 11 2016 10:30:00 GMT+0200 (EET)]

**Comment by jkbrzt** [comment]
`interval` It's an integer argument, so passing a string incorrect
