### ISSUE TITLE
v 2.7.1 is not downloadable from npm

### ISSUE THREAD

**Issue by KrakenTyio** [jkbrzt/rrule#532]
Version 2.7.1 is not downloadable form npm and raise error

**Comment by davidgoli** [comment]
I see no evidence in your errors that you're not able to _download_ rrule, but note this breaking change in 2.7.0:

```
BREAKING CHANGE Removes default export in favor of named exports
```

It looks like your code is still importing via the default export. You'll need to change `import RRule from 'rrule'` to `import { RRule } from 'rrule'` in your codebase. This is why this was a minor version release.

**Comment by KrakenTyio** [comment]
Weird, locking version on 2.7.0 working well
