### ISSUE TITLE
rrule.min.js is offline

### ISSUE THREAD

**Issue by KlaasVanHoeckROC** [jkbrzt/rrule#595]
### Reporting an issue

Thank you for taking an interest in `rrule`! Please include the following in
your report:

rrule.min.js file gives a 404. Not reachable in any way. Even links in read.me are offline

**Comment by davidgoli** [comment]
I've removed the reference to these files in the README. If you want to manually download them, you'll have to do so from npm: https://www.npmjs.com/package/rrule?activeTab=code
