### ISSUE TITLE
Millisecond precision start dates 

### ISSUE THREAD

**Issue by paulbalomiri** [jkbrzt/rrule#90]
In the code below i calculate the single `RRule.all()` result using different  frequencies. In all cases `dtstart` differs by only `1` millisecond, but the result differs by a whole frequency period.

I think the result should differ by the same amount (1 millisecond) in each case.

Admittedly i did not check the spec, but it would be a surprise if the spec required this behaviour.

```js
ret=[RRule.YEARLY, RRule.MONTHLY, RRule.DAILY, RRule.MINUTELY, RRule.SECONDLY].map(function(freq) {
    return [new Date(1420063200000), new Date(1420063200001)].map(
        function(dtstart) {
            return new RRule({
                dtstart: dtstart,
                freq: freq,
                count: 1
            }).all()[0]
        })
});
//EDIT: Removed superfluous ']'at the end
result=ret.map(function(cmp){return cmp[1].getTime()-cmp[0].getTime()});

```
`result`now contains:
```
[31536000000, 2678400000, 86400000, 60000, 1000]
```
but the expected result would be an `Array` containing only `1` milisecond values.

Could you confirm that it's not intended? I cannot give a timeframe, but i intend a PR.

Thanks for this very nessesary lib!

**Comment by paulbalomiri** [comment]
Hope you will accept the PR

**Comment by paulbalomiri** [comment]
The implications (besides solving this issue) are, as far as i can tell:

* The >= comparisions in iter [rrule.js#L1194](https://github.com/paulbalomiri/rrule/blob/pr-issue90/lib/rrule.js#L1194) and [rrule.js#L1220](https://github.com/paulbalomiri/rrule/blob/pr-issue90/lib/rrule.js#L1220) now work for offsets > 0
* Cache invalidation would need to account for milliseconds as well, but i think the cache cannot be invalidated anyways, except by creating a new instance of rrule. 
* the results now have an offset from whole which is different from what it used to be. 
*Before this patch, if one supplied a `dtstart %1000 !=0` the result was:
  * All recurrences were `rec%1000==0`
  * The first recurrence was skipped because the comparisons in the lines mentioned before would fail.
I think that this change has only correcting implications on the result set because:
* In the case of `dtstart%1000==0` there is no change
* In the case of `(x= dtstart`%1000) >0'
 * **before**:
     * The first Interval did not start at `dtstart` for 'rr.all()'
     * rr.before(rr.after(rr.options.dtstart)) == null 
     * The reason it worked without supplying dtstart is that you set the milliseconds programatically to 0.
  * **after**
    * This consistently holds `rr.before(rr.after(rr.options.dtstart))==rr.options.dtstart.getTime()`

**Comment by paulbalomiri** [comment]
Also a note on memory consumption, and the reason i initially named getMilliseconds getSubSeconds

The `datutil.Time` proto could only store a single millis integer and calculate the components on request (`get...`). I think the nesesary calculation (one integer division + one modulo calculation) would - id at all- be only marginally more time consuming than a property access.

This would open the way to a precision higher than milliseconds (thus my initial getSubSeconds), if RRutil is used with a custom Date implementation. and the %1000 is read on construction time from ` new Date(0).setSeconds(1) - new Date(0)`

**Comment by paulbalomiri** [comment]
Could you please change the title of this issue to **Resultset for sub-second precision start dates** or anything more meaningful and less typo-ed :). Sorry for that.

**Comment by jakubroztocil** [comment]
Thank you for the explanation :+1:
